"""
=============================================================================
Script: GPT-4 Assisted Cluster Labelling
Facebook Reactions COVID-19 India — Doctoral Thesis
Author: Sawood Anwar | University of Urbino Carlo Bo
Publication: Frontiers in Sociology, 2024 | DOI: 10.3389/fsoc.2024.1379265

Model used: gpt-4-0125-preview (GPT-4 Turbo, January 25 2024)
  - Context window: 128,000 tokens
  - Max output: 4,096 tokens
  - LMSys Arena Elo Score: 1245
  - HumanEval: 76.5%

Pipeline:
  a) Prompt Engineering  — COVID-19/India-contextualised prompt (refined iteratively)
  b) Cluster Sampling    — representative URL samples per cluster (token-budget aware)
  c) Label Generation    — chat completion endpoint → concise descriptive label
  d) Label Validation    — manual review of every generated label

See Thesis Chapter 4, Section 4.3.4 (pp. 64–65) and Appendix C, Table 1
=============================================================================

Required packages:
    pip install openai pandas tqdm loguru

Environment variables required:
    OPENAI_UNIURB_ORG_ID       — your OpenAI organisation ID
    OPENAI_VERA_PROJ_ID_API_KEY — your OpenAI project API key
"""

import os
import time
import json
import pandas as pd
from pathlib import Path
from tqdm import tqdm
from loguru import logger
from openai import OpenAI

# =============================================================================
# Configuration
# =============================================================================
config = {
    "model":           "gpt-4-0125-preview",  # Exact model used in thesis
    "max_tokens":      200,                    # Label output token budget
    "temperature":     0.3,                    # Low temp for consistent labels
    "samples_per_cluster": 10,                 # URLs sampled per cluster
    "sleep_between_calls": 1.0,                # Seconds between API calls
    "retry_attempts":  3,
}

# Logging
log_dir = Path(".logs")
log_dir.mkdir(exist_ok=True)
logger.add(log_dir / "labelling_{time}.log", rotation="1 day")

# OpenAI client
client = OpenAI(
    organization=os.environ.get("OPENAI_UNIURB_ORG_ID"),
    api_key=os.environ.get("OPENAI_VERA_PROJ_ID_API_KEY"),
)


# =============================================================================
# Step (a): Prompt Engineering
# Thesis: "We developed the Prompt which is based on COVID-19 queries
# within the context of India. It had been refined till the output came
# out with the relevancy of query design." (p. 64)
# =============================================================================
SYSTEM_PROMPT = """You are an expert media analyst specialising in COVID-19 news coverage in India.
You will be given a set of news article URLs from major Indian media outlets (Times of India,
The Hindu, Indian Express, Hindustan Times) that belong to the same thematic cluster.

Your task is to generate a concise, descriptive label (3–7 words) that captures the
core topic or theme shared by these articles. The label must:
- Be specific to the Indian COVID-19 context
- Reflect the dominant news theme, not just mention COVID-19
- Be suitable as a cluster label in an academic publication
- Use title case

Respond with ONLY the label — no explanation, no punctuation at the end."""


def build_user_prompt(urls: list[str]) -> str:
    """Build the user message from sampled URLs for a cluster."""
    url_list = "\n".join([f"- {url}" for url in urls])
    return (
        f"Here are representative news article URLs from this cluster:\n\n"
        f"{url_list}\n\n"
        f"Generate a concise thematic label for this cluster."
    )


# =============================================================================
# Step (b): Cluster Sampling
# Thesis: "for each cluster, we fed a few representative samples of URLs
# to ensure the balance between the sample size and API token limits" (p. 64)
# =============================================================================
def sample_cluster_urls(data: pd.DataFrame, cluster_id: int,
                        n_samples: int) -> list[str]:
    cluster_data = data[data["cluster"] == cluster_id]
    n = min(n_samples, len(cluster_data))
    sampled = cluster_data.sample(n=n, random_state=42)

    # Prefer the 'link' or 'url' column from CrowdTangle export
    for col in ["link", "url", "URL", "Post URL"]:
        if col in sampled.columns:
            return sampled[col].dropna().tolist()

    # Fallback: use message text if no URL column
    return sampled["message"].dropna().tolist()


# =============================================================================
# Step (c): Label Generation via Chat Completion
# Thesis: "the label was generated by using the above process and it was
# the chat completion endpoint" (p. 64)
# =============================================================================
def generate_cluster_label(urls: list[str], cluster_id: int) -> str:
    user_prompt = build_user_prompt(urls)

    for attempt in range(1, config["retry_attempts"] + 1):
        try:
            response = client.chat.completions.create(
                model=config["model"],
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": user_prompt},
                ],
                max_tokens=config["max_tokens"],
                temperature=config["temperature"],
            )
            label = response.choices[0].message.content.strip()
            logger.info(f"Cluster {cluster_id}: '{label}'")
            return label

        except Exception as e:
            logger.error(f"Attempt {attempt} failed for cluster {cluster_id}: {e}")
            if attempt == config["retry_attempts"]:
                logger.error(f"All retries exhausted for cluster {cluster_id}")
                return f"Cluster_{cluster_id}_Unlabelled"
            time.sleep(attempt * 2)  # exponential backoff

    return f"Cluster_{cluster_id}_Unlabelled"


# =============================================================================
# Step (d): Label Validation
# Thesis: "we used a manual check-up to ensure every label is accordingly
# fit for its own" (p. 64)
# A validation flag is added to prompt manual review
# =============================================================================
def validate_labels(labels_df: pd.DataFrame) -> pd.DataFrame:
    """Flag labels that may need manual review."""
    labels_df["needs_review"] = (
        labels_df["label"].str.len() < 5 |          # Too short
        labels_df["label"].str.contains("Unlabelled") |  # Failed generation
        labels_df["label"].str.lower().str.contains("covid")  # Too generic
    )
    flagged = labels_df[labels_df["needs_review"]]
    if len(flagged) > 0:
        logger.warning(f"{len(flagged)} cluster labels flagged for manual review:")
        for _, row in flagged.iterrows():
            logger.warning(f"  Cluster {row['cluster_id']}: '{row['label']}'")
    else:
        logger.info("All labels passed validation check.")
    return labels_df


# =============================================================================
# Main Pipeline
# =============================================================================
def main():
    logger.info("=== GPT-4 Cluster Labelling Pipeline ===")

    # Check environment variables
    required_env = ["OPENAI_UNIURB_ORG_ID", "OPENAI_VERA_PROJ_ID_API_KEY"]
    missing = [v for v in required_env if not os.environ.get(v)]
    if missing:
        raise EnvironmentError(f"Missing environment variables: {', '.join(missing)}")

    # Load clustered posts (output of 02_kmeans_clustering_tsne.py)
    input_file = "results/clustered_posts.csv"
    if not os.path.exists(input_file):
        raise FileNotFoundError(
            f"Clustered data not found: {input_file}\n"
            "Please run 02_kmeans_clustering_tsne.py first."
        )

    data = pd.read_csv(input_file)
    cluster_ids = sorted(data["cluster"].unique())
    logger.info(f"Generating labels for {len(cluster_ids)} clusters")

    # Generate labels
    results = []
    for cluster_id in tqdm(cluster_ids, desc="Labelling clusters"):
        urls   = sample_cluster_urls(data, cluster_id, config["samples_per_cluster"])
        label  = generate_cluster_label(urls, cluster_id)
        n_posts = len(data[data["cluster"] == cluster_id])

        results.append({
            "cluster_id":  cluster_id,
            "label":       label,
            "n_posts":     n_posts,
            "sample_urls": json.dumps(urls),
        })
        time.sleep(config["sleep_between_calls"])

    # Build labels dataframe
    labels_df = pd.DataFrame(results)

    # Validate
    labels_df = validate_labels(labels_df)

    # Merge labels back into main data
    label_map  = dict(zip(labels_df["cluster_id"], labels_df["label"]))
    data["cluster_label"] = data["cluster"].map(label_map)

    # Save outputs
    output_dir = Path("results")
    output_dir.mkdir(exist_ok=True)

    labels_df.to_csv(output_dir / "cluster_labels.csv", index=False)
    data.to_csv(output_dir / "clustered_posts_labelled.csv", index=False)

    logger.info("Labels saved to results/cluster_labels.csv")
    logger.info("Labelled posts saved to results/clustered_posts_labelled.csv")
    logger.info("Pipeline complete. Please review flagged labels manually.")

    # Print summary table
    summary = labels_df[["cluster_id", "label", "n_posts", "needs_review"]]
    print("\n" + "="*60)
    print("CLUSTER LABEL SUMMARY")
    print("="*60)
    print(summary.to_string(index=False))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        raise
