# =============================================================================
# Script 06: GPT-4 Assisted Cluster Labelling
# Facebook Reactions COVID-19 India — Doctoral Thesis
# Author: Sawood Anwar | University of Urbino Carlo Bo
# Publication: Frontiers in Sociology, 2024 | DOI: 10.3389/fsoc.2024.1379265
#
# Model: gpt-4-0125-preview (GPT-4 Turbo, January 25 2024)
#   Context window : 128,000 tokens
#   Max output     : 4,096 tokens
#   LMSys Elo      : 1245
#   HumanEval      : 76.5%
#
# Four-step pipeline (Thesis Section 4.3.4, p. 64):
#   a) Prompt Engineering  — COVID-19/India-contextualised prompt
#   b) Cluster Sampling    — representative URL samples per cluster
#   c) Label Generation    — chat completion endpoint → concise label
#   d) Label Validation    — manual review flag
#
# See Thesis Chapter 4, Section 4.3.4 (pp. 64–65) and Appendix C, Table 1
# =============================================================================
# Required packages:
#   install.packages(c("httr", "jsonlite", "dplyr", "readr", "stringr"))
#
# Environment variables required:
#   OPENAI_UNIURB_ORG_ID           — your OpenAI organisation ID
#   OPENAI_VERA_PROJ_ID_API_KEY    — your OpenAI project API key
# =============================================================================

library(httr)
library(jsonlite)
library(dplyr)
library(readr)
library(stringr)

# =============================================================================
# Configuration
# =============================================================================
config <- list(
  model              = "gpt-4-0125-preview",  # Exact model used in thesis
  max_tokens         = 200,
  temperature        = 0.3,
  samples_per_cluster = 10,
  sleep_between_calls = 1.0,
  retry_attempts     = 3
)

# Read credentials from environment variables
openai_org_id <- Sys.getenv("OPENAI_UNIURB_ORG_ID")
openai_api_key <- Sys.getenv("OPENAI_VERA_PROJ_ID_API_KEY")

if (nchar(openai_org_id) == 0 || nchar(openai_api_key) == 0) {
  stop("Missing required environment variables: OPENAI_UNIURB_ORG_ID and/or OPENAI_VERA_PROJ_ID_API_KEY")
}

# =============================================================================
# Step (a): Prompt Engineering
# Thesis: "We developed the Prompt which is based on COVID-19 queries
# within the context of India. It had been refined till the output came
# out with the relevancy of query design." (p. 64)
# =============================================================================
system_prompt <- paste(
  "You are an expert media analyst specialising in COVID-19 news coverage in India.",
  "You will be given a set of news article URLs from major Indian media outlets",
  "(Times of India, The Hindu, Indian Express, Hindustan Times)",
  "that belong to the same thematic cluster.",
  "\n\nYour task is to generate a concise, descriptive label (3-7 words) that captures the",
  "core topic or theme shared by these articles. The label must:",
  "- Be specific to the Indian COVID-19 context",
  "- Reflect the dominant news theme, not just mention COVID-19",
  "- Be suitable as a cluster label in an academic publication",
  "- Use Title Case",
  "\n\nRespond with ONLY the label — no explanation, no punctuation at the end."
)

# =============================================================================
# Step (b): Cluster Sampling
# Thesis: "for each cluster, we fed a few representative samples of URLs
# to ensure the balance between the sample size and API token limits" (p. 64)
# =============================================================================
sample_cluster_urls <- function(data, cluster_id, n_samples) {
  cluster_data <- data %>% filter(cluster == cluster_id)
  n <- min(n_samples, nrow(cluster_data))
  sampled <- cluster_data %>% sample_n(n)

  # Prefer link/url column from CrowdTangle export
  url_cols <- c("link", "url", "URL", "Post URL")
  for (col in url_cols) {
    if (col %in% names(sampled)) {
      return(na.omit(sampled[[col]]))
    }
  }

  # Fallback: use message text
  return(na.omit(sampled$message))
}

# =============================================================================
# Step (c): Label Generation via Chat Completion
# Thesis: "the label was generated by using the above process and it was
# the chat completion endpoint" (p. 64)
# =============================================================================
generate_cluster_label <- function(urls, cluster_id) {
  url_list    <- paste("- ", urls, collapse = "\n")
  user_prompt <- paste0(
    "Here are representative news article URLs from this cluster:\n\n",
    url_list,
    "\n\nGenerate a concise thematic label for this cluster."
  )

  for (attempt in seq_len(config$retry_attempts)) {
    response <- tryCatch({
      POST(
        url     = "https://api.openai.com/v1/chat/completions",
        add_headers(
          "Authorization"       = paste("Bearer", openai_api_key),
          "OpenAI-Organization" = openai_org_id,
          "Content-Type"        = "application/json"
        ),
        body = toJSON(list(
          model       = config$model,
          max_tokens  = config$max_tokens,
          temperature = config$temperature,
          messages    = list(
            list(role = "system", content = system_prompt),
            list(role = "user",   content = user_prompt)
          )
        ), auto_unbox = TRUE)
      )
    }, error = function(e) {
      message(sprintf("Attempt %d failed for cluster %d: %s", attempt, cluster_id, e$message))
      NULL
    })

    if (!is.null(response) && status_code(response) == 200) {
      result <- content(response, "parsed")
      label  <- trimws(result$choices[[1]]$message$content)
      message(sprintf("Cluster %d: '%s'", cluster_id, label))
      return(label)
    }

    Sys.sleep(attempt * 2)
  }

  warning(sprintf("All retries exhausted for cluster %d", cluster_id))
  return(paste0("Cluster_", cluster_id, "_Unlabelled"))
}

# =============================================================================
# Step (d): Label Validation
# Thesis: "we used a manual check-up to ensure every label is accordingly
# fit for its own" (p. 64)
# =============================================================================
validate_labels <- function(labels_df) {
  labels_df <- labels_df %>%
    mutate(needs_review = (
      nchar(label) < 5 |
      str_detect(label, "Unlabelled") |
      str_to_lower(label) == "covid-19 news coverage in india"
    ))

  flagged <- labels_df %>% filter(needs_review)
  if (nrow(flagged) > 0) {
    message(sprintf("%d cluster labels flagged for manual review:", nrow(flagged)))
    for (i in seq_len(nrow(flagged))) {
      message(sprintf("  Cluster %d: '%s'", flagged$cluster_id[i], flagged$label[i]))
    }
  } else {
    message("All labels passed validation check.")
  }

  return(labels_df)
}

# =============================================================================
# Main Pipeline
# =============================================================================

# Load clustered posts (output of Script 05)
input_file <- "results/clustered_posts.csv"
if (!file.exists(input_file)) {
  stop("Clustered data not found. Please run Script 05 first.")
}

data        <- read_csv(input_file, show_col_types = FALSE)
cluster_ids <- sort(unique(data$cluster))
message(sprintf("Generating labels for %d clusters...", length(cluster_ids)))

# Generate labels
results <- lapply(cluster_ids, function(cluster_id) {
  urls    <- sample_cluster_urls(data, cluster_id, config$samples_per_cluster)
  label   <- generate_cluster_label(urls, cluster_id)
  n_posts <- sum(data$cluster == cluster_id)
  Sys.sleep(config$sleep_between_calls)

  data.frame(
    cluster_id = cluster_id,
    label      = label,
    n_posts    = n_posts,
    stringsAsFactors = FALSE
  )
})

labels_df <- bind_rows(results)

# Validate labels
labels_df <- validate_labels(labels_df)

# Merge labels back into main data
data <- data %>%
  left_join(labels_df %>% select(cluster_id, label),
            by = c("cluster" = "cluster_id")) %>%
  rename(cluster_label = label)

# Save outputs
dir.create("results", showWarnings = FALSE)
write_csv(labels_df, "results/cluster_labels.csv")
write_csv(data,      "results/clustered_posts_labelled.csv")

message("Labels saved to results/cluster_labels.csv")
message("Labelled posts saved to results/clustered_posts_labelled.csv")
message("Pipeline complete. Review flagged labels manually before proceeding.")

# Print summary
cat("\n", strrep("=", 60), "\n")
cat("CLUSTER LABEL SUMMARY\n")
cat(strrep("=", 60), "\n")
print(labels_df[, c("cluster_id", "label", "n_posts", "needs_review")])
